In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Customer - Khách hàng

In [4]:
dfCustomer =  pd.read_csv("Master/customers.csv")

In [6]:
dfCustomer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121930 entries, 0 to 121929
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   customer_id          121930 non-null  int64
 1   zip                  121930 non-null  int64
 2   city                 121930 non-null  object
 3   signup_date          121930 non-null  object
 4   gender               121930 non-null  object
 5   age_group            121930 non-null  object
 6   acquisition_channel  121930 non-null  object
dtypes: int64(2), object(5)
memory usage: 6.5+ MB

In [8]:
dfCustomer.head()

,customer_id,zip,city,signup_date,gender,age_group,acquisition_channel
0,1,15201,Hai Phong,2021-12-30,Female,35-44,social_media
1,2,15201,Hai Phong,2013-12-27,Female,45-54,email_campaign
2,3,15201,Hai Phong,2018-07-24,Female,18-24,organic_search
3,4,15201,Hai Phong,2017-11-29,Male,35-44,referral
4,5,15201,Hai Phong,2022-09-23,Male,55+,organic_search

In [10]:
dfCustomer.tail()

,customer_id,zip,city,signup_date,gender,age_group,acquisition_channel
121925,157556,59936,Vung Tau,2016-03-03,Female,18-24,direct
121926,157557,59936,Vung Tau,2021-05-11,Female,45-54,social_media
121927,157558,59936,Vung Tau,2017-02-27,Female,25-34,referral
121928,157561,59937,Buon Ma Thuot,2018-10-15,Non-binary,45-54,paid_search
121929,157563,59937,Buon Ma Thuot,2018-08-23,Male,35-44,social_media

In [12]:
dfCustomer.describe()

         customer_id            zip
count  121930.000000  121930.000000
mean    78736.898663   50990.165595
std     45492.202886   26871.914605
min         1.000000    1001.000000
25%     39343.500000   28689.250000
50%     78784.500000   49835.000000
75%    118156.750000   73488.000000
max    157563.000000   99950.000000

In [14]:
dfCustomer.describe(include="O")

           city signup_date  gender age_group acquisition_channel
count    121930      121930  121930    121930              121930
unique       42        3941       3         5                   6
top     Cam Pha  2022-06-02  Female     25-34      organic_search
freq       4398          78   59640     36342               36450

In [16]:
dfCustomer.isnull().sum()

customer_id            0
zip                    0
city                   0
signup_date            0
gender                 0
age_group              0
acquisition_channel    0
dtype: int64

In [18]:
dfCustomer.duplicated().sum()

0

In [24]:
dfCustomer["city"].value_counts()

city
Cam Pha                4398
Thai Nguyen            4347
Phu Ly                 4243
Hanoi                  4240
Ha Long                4236
Bac Ninh               4172
Hai Phong              4170
Nam Dinh               4169
Bac Giang              4160
Ninh Binh              4081
Son Tay                4075
Viet Tri               4054
Uong Bi                4026
Dong Hoi               3912
Kon Tum                3838
Lao Cai                3807
Hoi An                 3760
Phan Thiet             3749
Phan Rang-Thap Cham    3734
Hue                    3719
Tuy Hoa                3674
Da Nang                3616
Quang Ngai             3616
Tam Ky                 3562
Quy Nhon               3556
Nha Trang              3550
Ho Chi Minh City       1359
Vinh Long              1336
Pleiku                 1253
Vung Tau               1251
Da Lat                 1243
Can Tho                1214
Bac Lieu               1211
Ca Mau                 1211
Soc Trang              1208
My Tho                 1198
Long Xuyen             1194
Ben Tre                1179
Bien Hoa               1173
Buon Ma Thuot          1167
Tra Vinh               1138
Rach Gia               1131
Name: count, dtype: int64

In [26]:
dfCustomer["gender"].value_counts()

gender
Female        59640
Male          57457
Non-binary     4833
Name: count, dtype: int64

In [28]:
    dfCustomer["age_group"].value_counts()

age_group
25-34    36342
35-44    31920
45-54    23172
18-24    17039
55+      13457
Name: count, dtype: int64

In [30]:
dfCustomer["acquisition_channel"].value_counts()

acquisition_channel
organic_search    36450
social_media      24448
paid_search       24285
email_campaign    14674
referral          12270
direct             9803
Name: count, dtype: int64

## geography - Địa lý

In [34]:
dfGeo  = pd.read_csv("Master/geography.csv")
dfGeo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39948 entries, 0 to 39947
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   zip       39948 non-null  int64
 1   city      39948 non-null  object
 2   region    39948 non-null  object
 3   district  39948 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.2+ MB

In [36]:
dfGeo.describe()

                zip
count  39948.000000
mean   50895.084735
std    27042.257341
min        1.000000
25%    28279.500000
50%    49876.500000
75%    73526.250000
max    99950.000000

In [38]:
dfGeo.describe(include = "O")

           city region      district
count     39948  39948         39948
unique       42      3            39
top     Cam Pha   East  District #25
freq       1403  18929          1597

In [40]:
dfGeo.isnull().sum()

zip         0
city        0
region      0
district    0
dtype: int64

In [42]:
dfGeo.duplicated().sum()

0

## products - Danh mục sản phẩm

In [44]:
dfProduct = pd.read_csv("Master/products.csv")
dfProduct.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2412 entries, 0 to 2411
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    2412 non-null   int64
 1   product_name  2412 non-null   object
 2   category      2412 non-null   object
 3   segment       2412 non-null   object
 4   size          2412 non-null   object
 5   color         2412 non-null   object
 6   price         2412 non-null   float64
 7   cogs          2412 non-null   float64
dtypes: float64(2), int64(1), object(5)
memory usage: 150.9+ KB

In [50]:
dfProduct.head()

,product_id,product_name,category,segment,size,color,price,cogs
0,536,SaigonFlex UC-01,Streetwear,Everyday,S,green,11059.650000,9704.842875
1,537,SaigonFlex UC-02,Streetwear,Everyday,M,silver,9523.076013,5393.870254
2,538,SaigonFlex UC-03,Streetwear,Everyday,L,pink,15951.633158,11371.919278
3,539,SaigonFlex UC-04,Streetwear,Everyday,XL,yellow,15753.717299,8573.172954
4,540,SaigonFlex UC-05,Streetwear,Everyday,S,red,15766.334536,14063.570406

## promotions - Chương trình khuyến mã

In [48]:
dfpromotions = pd.read_csv("Master/promotions.csv")
dfpromotions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   promo_id             50 non-null     object
 1   promo_name           50 non-null     object
 2   promo_type           50 non-null     object
 3   discount_value       50 non-null     float64
 4   start_date           50 non-null     object
 5   end_date             50 non-null     object
 6   applicable_category  10 non-null     object
 7   promo_channel        50 non-null     object
 8   stackable_flag       50 non-null     int64
 9   min_order_value      50 non-null     int64
dtypes: float64(1), int64(2), object(7)
memory usage: 4.0+ KB

In [56]:
dfpromotions.head()

,promo_id,promo_name,promo_type,discount_value,start_date,end_date,applicable_category,promo_channel,stackable_flag,min_order_value
0,PROMO-0001,Spring Sale 2013,percentage,12.0,2013-03-18,2013-04-17,All,email,1,0
1,PROMO-0002,Mid-Year Sale 2013,percentage,18.0,2013-06-23,2013-07-22,All,online,0,0
2,PROMO-0003,Fall Launch 2013,percentage,10.0,2013-08-30,2013-10-02,All,email,0,0
3,PROMO-0004,Year-End Sale 2013,percentage,20.0,2013-11-18,2014-01-02,All,all_channels,0,50000
4,PROMO-0005,Urban Blowout 2013,fixed,50.0,2013-07-30,2013-09-02,Streetwear,online,0,150000

In [54]:
dfpromotions.fillna("All", inplace=True)