In [147]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [149]:
dfOrder =  pd.read_csv("Transaction/orders.csv")
dfOrder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 646945 entries, 0 to 646944
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        646945 non-null  int64
 1   order_date      646945 non-null  object
 2   customer_id     646945 non-null  int64
 3   zip             646945 non-null  int64
 4   order_status    646945 non-null  object
 5   payment_method  646945 non-null  object
 6   device_type     646945 non-null  object
 7   order_source    646945 non-null  object
dtypes: int64(3), object(5)
memory usage: 39.5+ MB

In [150]:
dfOrder["order_date"] = pd.to_datetime(dfOrder["order_date"])

In [151]:
dfOrder.duplicated().sum()

0

In [152]:
dfOrder.sort_values(by = ["customer_id", "order_date"])

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source
4023,5280,2012-07-25,1,15201,delivered,cod,desktop,paid_search
143252,184922,2014-05-31,1,15201,returned,credit_card,mobile,referral
238890,308113,2015-07-31,1,15201,delivered,cod,mobile,paid_search
374571,483190,2017-04-23,1,15201,delivered,cod,mobile,paid_search
544446,702081,2020-02-24,1,15201,delivered,credit_card,mobile,organic_search
...,...,...,...,...,...,...,...,...
549990,709267,2020-04-11,157563,59937,delivered,credit_card,mobile,email_campaign
557438,718824,2020-05-29,157563,59937,delivered,credit_card,mobile,social_media
559725,721751,2020-06-22,157563,59937,delivered,paypal,tablet,organic_search
591841,763157,2021-05-27,157563,59937,delivered,credit_card,mobile,social_media
637881,822601,2022-08-31,157563,59937,cancelled,cod,desktop,social_media

In [153]:
dfOrder[dfOrder["customer_id"] == 1]

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source
4023,5280,2012-07-25,1,15201,delivered,cod,desktop,paid_search
143252,184922,2014-05-31,1,15201,returned,credit_card,mobile,referral
238890,308113,2015-07-31,1,15201,delivered,cod,mobile,paid_search
374571,483190,2017-04-23,1,15201,delivered,cod,mobile,paid_search
544446,702081,2020-02-24,1,15201,delivered,credit_card,mobile,organic_search
586950,756884,2021-04-24,1,15201,paid,credit_card,desktop,social_media

In [156]:
dfOrder.head()

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source
0,1,2012-07-04,58578,1109,delivered,credit_card,desktop,paid_search
1,2,2012-07-04,58621,1330,returned,cod,mobile,paid_search
2,3,2012-07-04,58811,1473,delivered,credit_card,desktop,direct
3,4,2012-07-04,59453,2360,delivered,credit_card,desktop,referral
4,6,2012-07-06,57821,2886,delivered,paypal,mobile,email_campaign

In [158]:
# Trong số các khách hàng có nhiều hơn một đơn hàng, trung vị số ngày giữa hai lần
# mua liên tiếp (inter-order gap) xấp xỉ là bao nhiêu? (Tính từ orders.csv)
dfCustomermore2Order = dfOrder.groupby("customer_id")["order_date"].value_counts().reset_index().sort_values(by = ["customer_id", "order_date"])

In [160]:
dfCustomermore2Order2 = dfOrder.groupby("customer_id")["order_date"].unique()

In [163]:
dfCustomermore2Order[dfCustomermore2Order["customer_id"] == 157563]

        customer_id order_date  count
641844       157563 2012-07-16      1
641845       157563 2013-07-18      1
641846       157563 2013-12-29      1
641847       157563 2013-12-30      1
641848       157563 2015-01-29      1
641849       157563 2015-04-13      1
641850       157563 2015-05-02      1
641851       157563 2015-05-10      1
641852       157563 2015-05-25      1
641853       157563 2016-12-15      1
641854       157563 2016-12-17      1
641855       157563 2017-02-22      1
641856       157563 2017-04-03      1
641857       157563 2017-07-01      1
641858       157563 2018-03-02      1
641859       157563 2018-08-20      1
641860       157563 2019-08-30      1
641861       157563 2020-04-11      1
641862       157563 2020-05-29      1
641863       157563 2020-06-22      1
641864       157563 2021-05-27      1
641865       157563 2022-08-31      1

In [166]:
dfCustomermore2Order2.values

array([<DatetimeArray>
       ['2012-07-25 00:00:00', '2014-05-31 00:00:00', '2015-07-31 00:00:00',
        '2017-04-23 00:00:00', '2020-02-24 00:00:00', '2021-04-24 00:00:00']
       Length: 6, dtype: datetime64[ns]                                     ,
       <DatetimeArray>
       ['2013-09-20 00:00:00', '2013-10-28 00:00:00', '2014-11-13 00:00:00',
        '2022-07-06 00:00:00']
       Length: 4, dtype: datetime64[ns]                                     ,
       <DatetimeArray>
       ['2012-08-27 00:00:00', '2012-11-24 00:00:00', '2013-07-29 00:00:00']
       Length: 3, dtype: datetime64[ns]                                     ,
       ..., <DatetimeArray>
            ['2017-06-02 00:00:00']
            Length: 1, dtype: datetime64[ns],
       <DatetimeArray>
       ['2012-07-18 00:00:00', '2013-04-21 00:00:00', '2013-07-02 00:00:00',
        '2013-10-03 00:00:00', '2014-11-12 00:00:00', '2014-12-30 00:00:00',
        '2015-06-30 00:00:00', '2015-08-09 00:00:00', '2016-05-15 00:00:00',
        '2016-05-24 00:00:00', '2016-11-30 00:00:00', '2016-12-14 00:00:00',
        '2017-04-03 00:00:00', '2017-06-30 00:00:00', '2017-08-13 00:00:00',
        '2018-03-11 00:00:00', '2019-05-11 00:00:00', '2019-05-10 00:00:00',
        '2020-03-16 00:00:00', '2020-07-10 00:00:00', '2020-08-24 00:00:00']
       Length: 21, dtype: datetime64[ns]                                    ,
       <DatetimeArray>
       ['2012-07-16 00:00:00', '2013-07-18 00:00:00', '2013-12-29 00:00:00',
        '2013-12-30 00:00:00', '2015-01-29 00:00:00', '2015-04-13 00:00:00',
        '2015-05-02 00:00:00', '2015-05-10 00:00:00', '2015-05-25 00:00:00',
        '2016-12-15 00:00:00', '2016-12-17 00:00:00', '2017-02-22 00:00:00',
        '2017-04-03 00:00:00', '2017-07-01 00:00:00', '2018-03-02 00:00:00',
        '2018-08-20 00:00:00', '2019-08-30 00:00:00', '2020-04-11 00:00:00',
        '2020-05-29 00:00:00', '2020-06-22 00:00:00', '2021-05-27 00:00:00',
        '2022-08-31 00:00:00']
       Length: 22, dtype: datetime64[ns]                                    ],
      dtype=object)

In [167]:
dfCustomermore2Order2[1]
# 157563

<DatetimeArray>
['2012-07-25 00:00:00', '2014-05-31 00:00:00', '2015-07-31 00:00:00',
 '2017-04-23 00:00:00', '2020-02-24 00:00:00', '2021-04-24 00:00:00']
Length: 6, dtype: datetime64[ns]

In [229]:
listDay = []
for i in dfCustomermore2Order2.index:
    #     # print(dfCustomermore2Order2[i])
    #     for j in range (1, len(dfCustomermore2Order2[i]), 1):
    #         res = (dfCustomermore2Order2[i][j] - dfCustomermore2Order2[i][j-1]).days
    #         print(i, res)
    if len(dfCustomermore2Order2[i]) >= 2:
        for j in range (1, len(dfCustomermore2Order2[i]), 1):
            # print(i ,dfCustomermore2Order2[i][j])
            res = (dfCustomermore2Order2[i][j] - dfCustomermore2Order2[i][j-1]).days
            if res not in listDay:
                listDay.append(res)

In [231]:
np.median(listDay)

1639.0

In [215]:
import pandas as pd

dfOrder['gap'] = dfOrder.groupby('customer_id')['order_date'].diff().dt.days

# lọc khách có >1 đơn (gap != null)
gaps = dfOrder['gap'].dropna()

# median
median_gap = gaps.median()

print(median_gap)

144.0

In [233]:
 tes =dfOrder.groupby('customer_id')['order_date'].diff().dt.days

In [235]:
tes[1]

nan